Repository TomBenDor/AP1, pull requests merged in 2021-09, with the labels that each got.

#11 Fixes #8
  ex3/server/main.cpp
Labels: enhancement

#18 Fixes #12
  ex3/client/TCPClient.cpp
  ex3/client/TCPClient.h
  ex3/client/main.cpp
  ex3/server/Iris.cpp
  ex3/server/TCPServer.cpp
  ex3/server/TCPServer.h
  ex3/server/main.cpp
  ex3/utils.cpp
  ex3/utils.h
Labels: organization

#21 Update readme.md
  ex2/readme.md
Labels: bug

#25 Iris have unlimited amount of coordinates (Fixes #16)
  ex3/server/Iris.cpp
  ex3/server/Iris.h
  ex3/server/main.cpp
Labels: enhancement, organization

#26 Distance metrics (Fixes #7)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  ex3/CMakeLists.txt
  ex3/server/ChebyshevDistance.h
  ex3/server/Classifiable.h
  ex3/server/Classifier.h
  ex3/server/Distance.h
  ex3/server/EuclideanDistance.h
  ex3/server/Iris.cpp
  ex3/server/Iris.h
  ex3/server/KnnClassifier.h
  ex3/server/ManhattanDistance.h
  ex3/server/main.cpp
Labels: enhancement, organization

#27 Using std::thread (Fixes #24)
  ex3/server/ChebyshevDistance.h
  ex3/server/EuclideanDistance.h
  ex3/server/ManhattanDistance.h
  ex3/server/main.cpp
Labels: organization

#35 2 thread client
  ex3/client/main.cpp
  ex3/server/main.cpp
  ex3/utils.cpp
  ex3/utils.h
Labels: enhancement

#37 Command & Default IO abstract classes
  ex3/CMakeLists.txt
  ex3/server/Command.cpp
  ex3/server/Command.h
  ex3/server/DefaultIO.h
Labels: organization

#39 Added StandardIO and fixed the encapsulation in DefaultIO
  ex3/CMakeLists.txt
  ex3/server/DefaultIO.h
  ex3/server/StandardIO.cpp
  ex3/server/StandardIO.h
Labels: organization

#43 Fixed the Command class
  ex3/server/Command.cpp
  ex3/server/Command.h
Labels: bug

#42 Option number 2
  ex3/CMakeLists.txt
  ex3/server/ChangeAlgoSettings.h
  ex3/server/ChebyshevDistance.h
  ex3/server/Command.cpp
  ex3/server/Distance.h
  ex3/server/EuclideanDistance.h
  ex3/server/KnnClassifier.h
  ex3/server/ManhattanDistance.h
  ex3/server/main.cpp
Labels: enhancement

#45 Option number 1
  ex3/CMakeLists.txt
  ex3/server/Command.cpp
  ex3/server/Iris.cpp
  ex3/server/Iris.h
  ex3/server/UploadUnclassified.cpp
  ex3/server/UploadUnclassified.h
Labels: enhancement

#46 Cleanup
  ex3/CMakeLists.txt
  ex3/client/CMakeLists.txt
  ex3/client/main.cpp
  ex3/server/CMakeLists.txt
  ex3/server/Iris.cpp
  ex3/server/KnnClassifier.h
  ex3/server/commands/ChangeAlgoSettingsCommand.h
  ex3/server/commands/Command.cpp
  ex3/server/commands/Command.h
  ex3/server/commands/UploadUnclassifiedCommand.cpp
  ex3/server/commands/UploadUnclassifiedCommand.h
  ex3/server/main.cpp
  ex3/server/metrics/ChebyshevDistance.h
  ex3/server/metrics/Distance.h
  ex3/server/metrics/EuclideanDistance.h
  ex3/server/metrics/ManhattanDistance.h
  ex3/utils.cpp
  ex3/utils.h
Labels: organization

#47 Change csv files to unix style
  ex3/client/data/Unclassified.csv
  ex3/server/data/classified.csv
Labels: bug

#49 Option No. 2 - Changed parameters delim
  ex3/server/commands/ChangeAlgoSettingsCommand.h
Labels: bug

#52 SocketIO implementation
  ex3/server/CMakeLists.txt
  ex3/server/IO/DefaultIO.h
  ex3/server/IO/SocketIO.cpp
  ex3/server/IO/SocketIO.h
  ex3/server/IO/StandardIO.cpp
  ex3/server/IO/StandardIO.h
  ex3/server/commands/Command.h
  ex3/server/main.cpp
Labels: enhancement

#50 Confusion matrix
  ex3/server/CMakeLists.txt
  ex3/server/ConfusionMatrix.cpp
  ex3/server/ConfusionMatrix.h
  ex3/server/Iris.cpp
  ex3/server/Iris.h
  ex3/server/commands/ConfusionMatrixCommand.cpp
  ex3/server/commands/ConfusionMatrixCommand.h
Labels: enhancement

#55 Main menu
  ex3/client/main.cpp
  ex3/server/CMakeLists.txt
  ex3/server/ClientData.h
  ex3/server/ConfusionMatrix.cpp
  ex3/server/KnnClassifier.h
  ex3/server/commands/ChangeAlgoSettingsCommand.h
  ex3/server/commands/Command.cpp
  ex3/server/commands/Command.h
  ex3/server/commands/ConfusionMatrixCommand.cpp
  ex3/server/commands/ConfusionMatrixCommand.h
  ex3/server/commands/UploadUnclassifiedCommand.cpp
  ex3/server/commands/UploadUnclassifiedCommand.h
  ex3/server/main.cpp
  ex3/utils.cpp
Labels: enhancement, organization

#57 Option number 3
  ex3/server/CMakeLists.txt
  ex3/server/ClientData.h
  ex3/server/commands/ClassifyDataCommand.h
  ex3/server/commands/Command.h
  ex3/server/commands/ConfusionMatrixCommand.h
  ex3/server/commands/UploadUnclassifiedCommand.h
  ex3/server/main.cpp
Labels: enhancement

#58 Option number 4 - Display Results
  ex3/server/CMakeLists.txt
  ex3/server/commands/DisplayResultsCommand.h
  ex3/server/main.cpp
Labels: enhancement

#59 KNNClassifier makes arbitrary decisions
  ex3/server/KnnClassifier.h
Labels: bug

#61 Using DefaultIO instead of SocketIO
  ex3/server/commands/UploadUnclassifiedCommand.h
  ex3/server/main.cpp
Labels: organization

#62 Fixed classifying multiple times
  ex3/server/KnnClassifier.h
Labels: bug

#63 Changing to stable_sort
  ex3/server/KnnClassifier.h
Labels: bug

#64 Fixed unpredictable classifications
  ex3/server/KnnClassifier.h
Labels: bug

#65 Added CLI class
  ex3/server/CLI.h
  ex3/server/CMakeLists.txt
  ex3/server/main.cpp
Labels: organization

#67 Using unique_ptr
  ex3/server/CLI.h
  ex3/server/KnnClassifier.h
  ex3/server/commands/ChangeAlgoSettingsCommand.h
  ex3/server/main.cpp
Labels: enhancement
